### ISSUE TITLE
After rm -rf ~/.signet/remotes/myRemoteName, reference still exists

### ISSUE THREAD

**Issue by dmvaldman** [chromakode/signet#7]
After `rm -rf ~/.signet/remotes/keybase` and adding a new remote with the same name, I get the warning

`warning A remote named "keybase" already exists. Skipping.`

**Comment by chromakode** [comment]
Thanks, I'll look into this and add some tests.

**Comment by chromakode** [comment]
Ah, I think I may know what is going on here. If you run `sig list` you'll see that there is still a remote entry for "keybase". Remotes are stored in the main configuration file, `~/.signet/config`. Removing the remote directory doesn't remove the configured remote -- you have to `sig remote remove keybase` as well.

I recommended to remove the directory in my [tweet](https://twitter.com/chromakode/status/708498132703666176) because there was [another issue](https://github.com/chromakode/signet/issues/6) that would cause `sig` to crash on startup if remote repo files weren't valid JSON.

Does this clarify what you're experiencing? Does the behavior of managing remotes with `sig remote add`/`sig remote remove` make sense?

**Comment by dmvaldman** [comment]
Ah yes, makes total sense and fixed my issue. Thanks!
